apiVersion: v1
kind: Service
metadata:
  name: estima
  labels:
    app.kubernetes.io/part-of: estima-test
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: estima
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: atlas
  labels:
    app.kubernetes.io/part-of: estima-test
    app.kubernetes.io/component: legacy-alias
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: estima
  ports:
    - name: http
      port: 8080
